[package]
name = "casper-server-agent"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
actix-rt = "2.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.33", features = ["full"] }
env_logger = "0.10"
log = "0.4"
sysinfo = "0.29"
